name: Build and Push to Google Container Registry

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
    build-push-container:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v4'

            - name: Authenticate to Google Cloud
              id: auth
              uses: google-github-actions/auth@v2
              with:
                  service_account: githubactions@next-log-parser.iam.gserviceaccount.com

            - uses: RafikFarhad/push-to-gcr-github-action@v4.1
              with:
                  gcloud_service_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
                  registry: gcr.io/next-log-parser/next-log-parser
                  project_id: next-log-parser
                  image_name: next-log-parser
                  image_tag: latest
                  dockerfile: ./Dockerfile
                  context: .
